[package]
name = "predictables-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "pareto_sort"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20.2", features = ["extension-module"] }
rayon = "1.8.1"
